# Site settings
title: PHPSC
title_long: Grupo de Usuários de PHP de Santa Catarina
email: contato@phpsc.com.br
description: > # this means to ignore newlines until "baseurl:"
  PHPSC - Grupo de Usuários de PHP de Santa catarina.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.phpsc.com.br" # the base hostname & protocol for your site

# Social
twitter_username: PHP_SC
github_username: PHPSC
facebook_username: santa.catarina.elephants
linkedin_id: 3632979

# Build settings
highlighter: rouge
timezone: America/Sao_Paulo
permalink: pretty

# Pagination
paginate: 3
pagination_path: "/:num"

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-paginate

sass:
  style: compressed

exclude: [vendor]
